kind: pipeline
type: exec
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: test
  commands:
  - mkdir -p $HOMEPATH/.docker; echo $IMAGE_PULL_SECRETS > $HOMEPATH/.docker/config.json
  - make test
  environment:
    VERSION: ${DRONE_TAG:-latest}-linux-amd64
    DEV_REGISTRY:
      from_secret: dev_registry
    DRYCC_REGISTRY:
      from_secret: drycc_registry
    IMAGE_PULL_SECRETS:
      from_secret: container_pull_secrets
  when:
    event:
    - push
    - tag
    - pull_request

- name: publish
  commands:
  - echo $CONTAINER_PASSWORD | docker login $DRYCC_REGISTRY --username $CONTAINER_USERNAME --password-stdin > /dev/null 2>&1
  - make docker-build docker-immutable-push
  environment:
    REDIS_SENTINEL_VERSION: ${DRONE_TAG:-6.2}
    VERSION: ${DRONE_TAG:-6.2}-linux-amd64
    DEV_REGISTRY:
      from_secret: dev_registry
    DRYCC_REGISTRY:
      from_secret: drycc_registry
    CONTAINER_USERNAME:
      from_secret: container_username
    CONTAINER_PASSWORD:
      from_secret: container_password
  when:
    event:
    - push
    - tag

---
kind: pipeline
type: exec
name: linux-arm64

platform:
  arch: arm64
  os: linux

steps:
- name: publish
  commands:
  - echo $CONTAINER_PASSWORD | docker login $DRYCC_REGISTRY --username $CONTAINER_USERNAME --password-stdin > /dev/null 2>&1
  - make docker-build docker-immutable-push
  environment:
    REDIS_SENTINEL_VERSION: ${DRONE_TAG:-6.2}
    VERSION: ${DRONE_TAG:-6.2}-linux-arm64
    DEV_REGISTRY:
      from_secret: dev_registry
    DRYCC_REGISTRY:
      from_secret: drycc_registry
    CONTAINER_USERNAME:
      from_secret: container_username
    CONTAINER_PASSWORD:
      from_secret: container_password
  when:
    event:
    - push
    - tag

---
kind: pipeline
type: docker
name: manifest
image_pull_secrets:
- container_pull_secrets

steps:

- name: generate manifest
  image: registry.drycc.cc/drycc/python-dev
  pull: always
  commands:
  - sed -i "s/registry.drycc.cc/$${DRYCC_REGISTRY}/g" .drone/manifest.tmpl
  - sed -i "s/canary/$${REDIS_SENTINEL_VERSION}/g" .drone/manifest.tmpl
  environment:
    DEV_REGISTRY:
      from_secret: dev_registry
    DRYCC_REGISTRY:
      from_secret: drycc_registry
    REDIS_SENTINEL_VERSION: ${DRONE_TAG:-6.2}

- name: publish
  image: plugins/manifest
  settings:
    spec: .drone/manifest.tmpl
    username:
      from_secret: container_username
    password:
      from_secret: container_password
  environment:
    DEV_REGISTRY:
      from_secret: dev_registry
    DRYCC_REGISTRY:
      from_secret: drycc_registry

trigger:
  event:
  - pull_request
  - push
  - tag

depends_on:
- linux-amd64
- linux-arm64
